services:
  # Backend service
  - type: web
    name: therabot-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: your-api-key-here
        sync: false